// Interpreter.cpp
//
// Implementation of rapid::Interpreter. See Interpreter.hpp for an overview
// and documented limitations.
//
// Dispatch over expression/statement alternatives is done with dynamic_cast
// on the labeled context subclasses generated by ANTLR4 (ParenExprContext,
// AddExprContext, ...) rather than the visitor's std::any-based
// visitXxx()/accept() mechanism - this keeps the dispatch logic explicit and
// readable. ifStatement/testStatement walk ctx->children directly because
// ANTLR flattens repeated optional groups (THEN/ELSEIF/ELSE, CASE/DEFAULT)
// into single accessor vectors that lose branch boundaries.

#include "Interpreter.hpp"

#include "antlr4-runtime.h"

#include <cmath>
#include <iomanip>
#include <iostream>
#include <sstream>

namespace rapid {

Interpreter::Interpreter() {
    registerBuiltins();
}

// ===========================================================================
// Setup / entry point
// ===========================================================================

void Interpreter::run(RapidParser::RapidModuleContext* module, const std::string& entryProc) {
    auto* mod = module->moduleDeclaration();

    for (auto* rd : mod->routineDeclaration()) {
        if (auto* p = rd->procedureDeclaration()) {
            procedures_[Environment::normalize(p->IDENTIFIER()->getText())] = p;
        } else if (auto* f = rd->functionDeclaration()) {
            functions_[Environment::normalize(f->IDENTIFIER()->getText())] = f;
        }
        // trapDeclaration: error-handler traps aren't invoked by user code
        // and the grammar has nowhere to RAISE into them; skipped.
    }

    for (auto* dd : mod->dataDeclaration()) {
        declareData(dd, globals_);
    }

    auto it = procedures_.find(Environment::normalize(entryProc));
    if (it == procedures_.end()) {
        throw error("entry procedure '" + entryProc + "' not found");
    }

    Environment local(&globals_);
    bindArguments(it->second->parameterList(), nullptr, globals_, local);

    callStack_.push_back(it->second->IDENTIFIER()->getText());
    try {
        execStatements(it->second->statement(), local);
    } catch (ReturnSignal&) {
        // RETURN from the entry procedure: normal termination.
    } catch (ExitSignal&) {
        // EXIT: normal termination.
    } catch (GotoSignal& g) {
        auto err = error("label '" + g.label + "' not found in '" + entryProc + "'");
        callStack_.pop_back();
        throw err;
    }
    callStack_.pop_back();
}

void Interpreter::declareData(RapidParser::DataDeclarationContext* ctx, Environment& env) {
    const std::string name = ctx->IDENTIFIER()->getText();
    if (auto* initExpr = ctx->expression()) {
        env.declare(name, evalExpression(initExpr, env));
    } else {
        // No initializer: fall back to a type-appropriate default.
        // arrayDimension (sized-but-uninitialized arrays) is not honored yet;
        // such declarations get a scalar default instead of a sized array.
        env.declare(name, defaultValueForType(ctx->dataType()->getText()));
    }
}

Value Interpreter::defaultValueForType(const std::string& typeName) {
    const std::string t = Environment::normalize(typeName);
    if (t == "bool") return Value::boolean(false);
    if (t == "string") return Value::string("");
    return Value::num(0); // num and unknown record types
}

// ===========================================================================
// Statements
// ===========================================================================

void Interpreter::execStatements(const std::vector<RapidParser::StatementContext*>& stmts, Environment& env) {
    // Build a label -> index map for THIS list only. A GotoSignal whose
    // label isn't in this map is rethrown, so an enclosing execStatements()
    // (for the routine body, or an outer IF/FOR/WHILE) gets a chance to
    // find it - i.e. GOTO can jump out of a nested block to a label at an
    // enclosing level, but not into a nested block.
    std::unordered_map<std::string, size_t> labels;
    for (size_t i = 0; i < stmts.size(); ++i) {
        if (auto* lbl = stmts[i]->labelStatement()) {
            labels[Environment::normalize(lbl->IDENTIFIER()->getText())] = i;
        }
    }

    size_t i = 0;
    while (i < stmts.size()) {
        try {
            execStatement(stmts[i], env);
            ++i;
        } catch (GotoSignal& g) {
            auto it = labels.find(Environment::normalize(g.label));
            if (it == labels.end()) throw;
            i = it->second;
        }
    }
}

void Interpreter::execStatement(RapidParser::StatementContext* ctx, Environment& env) {
    if (auto* c = ctx->dataDeclaration())        { declareData(c, env); return; }
    if (auto* c = ctx->assignmentStatement())    { execAssignment(c, env); return; }
    if (auto* c = ctx->moveAbsJStatement())      { execMoveAbsJ(c, env); return; }
    if (auto* c = ctx->moveCStatement())         { execMoveC(c, env); return; }
    if (auto* c = ctx->moveJStatement())         { execMoveJ(c, env); return; }
    if (auto* c = ctx->moveLStatement())         { execMoveL(c, env); return; }
    if (auto* c = ctx->procedureCallStatement()) { execProcedureCall(c, env); return; }
    if (auto* c = ctx->ifStatement())            { execIf(c, env); return; }
    if (auto* c = ctx->forStatement())           { execFor(c, env); return; }
    if (auto* c = ctx->whileStatement())         { execWhile(c, env); return; }
    if (auto* c = ctx->testStatement())          { execTest(c, env); return; }
    if (auto* c = ctx->returnStatement())        { execReturn(c, env); return; }
    if (ctx->exitStatement())                    { throw ExitSignal{}; }
    if (auto* c = ctx->gotoStatement())          { throw GotoSignal{c->IDENTIFIER()->getText()}; }
    if (ctx->labelStatement())                   { return; } // marker only, handled in execStatements
    if (ctx->connectStatement()) {
        std::cerr << "[warn] CONNECT is not simulated, ignoring: " << ctx->getText() << std::endl;
        return;
    }
    if (auto* c = ctx->raiseStatement()) {
        const std::string err = c->IDENTIFIER() ? c->IDENTIFIER()->getText() : "ERR_UNSPECIFIED";
        throw error("unhandled RAISE " + err + " (TRAP/ERROR handlers are not modeled)");
    }
    if (ctx->retryStatement() || ctx->tryNextStatement()) {
        std::cerr << "[warn] RETRY/TRYNEXT outside an error handler, ignoring: " << ctx->getText() << std::endl;
        return;
    }
    throw error("unrecognized statement: " + ctx->getText());
}

void Interpreter::execAssignment(RapidParser::AssignmentStatementContext* ctx, Environment& env) {
    Value v = evalExpression(ctx->expression(), env);
    assignVariableReference(ctx->variableReference(), v, env);
}

// ---- IF / ELSEIF / ELSE ----------------------------------------------------

std::vector<Interpreter::IfBranch> Interpreter::splitIfBranches(RapidParser::IfStatementContext* ctx) {
    std::vector<IfBranch> branches;
    IfBranch current{nullptr, {}};
    bool collectingCondition = true; // true while we're between IF/ELSEIF and THEN

    for (auto* child : ctx->children) {
        if (auto* expr = dynamic_cast<RapidParser::ExpressionContext*>(child)) {
            if (collectingCondition) current.condition = expr;
            continue;
        }
        if (auto* stmt = dynamic_cast<RapidParser::StatementContext*>(child)) {
            current.body.push_back(stmt);
            continue;
        }
        if (auto* term = dynamic_cast<antlr4::tree::TerminalNode*>(child)) {
            const size_t type = term->getSymbol()->getType();
            if (type == RapidParser::THEN) {
                collectingCondition = false;
            } else if (type == RapidParser::ELSEIF) {
                branches.push_back(current);
                current = IfBranch{nullptr, {}};
                collectingCondition = true;
            } else if (type == RapidParser::ELSE) {
                branches.push_back(current);
                current = IfBranch{nullptr, {}}; // no condition => else-branch
                collectingCondition = false;
            }
            // IF / ENDIF: no action needed.
        }
    }
    branches.push_back(current);
    return branches;
}

void Interpreter::execIf(RapidParser::IfStatementContext* ctx, Environment& env) {
    for (auto& branch : splitIfBranches(ctx)) {
        if (branch.condition == nullptr || evalExpression(branch.condition, env).asBool()) {
            execStatements(branch.body, env);
            return;
        }
    }
}

// ---- FOR / WHILE ------------------------------------------------------------

void Interpreter::execFor(RapidParser::ForStatementContext* ctx, Environment& env) {
    const std::string varName = ctx->IDENTIFIER()->getText();
    auto exprs = ctx->expression();
    const double from = evalExpression(exprs[0], env).asNum();
    const double to = evalExpression(exprs[1], env).asNum();
    const double step = exprs.size() > 2 ? evalExpression(exprs[2], env).asNum() : 1.0;
    if (step == 0.0) throw error("FOR ... STEP 0 would loop forever");

    env.declare(varName, Value::num(from));
    auto body = ctx->statement();

    for (double v = from; (step > 0.0) ? (v <= to) : (v >= to); v += step) {
        *env.find(varName) = Value::num(v);
        execStatements(body, env);
    }
}

void Interpreter::execWhile(RapidParser::WhileStatementContext* ctx, Environment& env) {
    auto body = ctx->statement();
    while (evalExpression(ctx->expression(), env).asBool()) {
        execStatements(body, env);
    }
}

// ---- TEST / CASE / DEFAULT --------------------------------------------------

Interpreter::TestInfo Interpreter::splitTest(RapidParser::TestStatementContext* ctx) {
    TestInfo info;
    bool selectorCaptured = false;
    bool collectingValues = false;
    bool hasBuilding = false;
    TestCase building;
    std::vector<TestCase> cases;

    for (auto* child : ctx->children) {
        if (auto* expr = dynamic_cast<RapidParser::ExpressionContext*>(child)) {
            if (!selectorCaptured) {
                info.selector = expr;
                selectorCaptured = true;
            } else if (collectingValues && hasBuilding) {
                building.values.push_back(expr);
            }
            continue;
        }
        if (auto* stmt = dynamic_cast<RapidParser::StatementContext*>(child)) {
            if (hasBuilding) building.body.push_back(stmt);
            continue;
        }
        if (auto* term = dynamic_cast<antlr4::tree::TerminalNode*>(child)) {
            const size_t type = term->getSymbol()->getType();
            if (type == RapidParser::CASE) {
                if (hasBuilding) cases.push_back(building);
                building = TestCase{};
                hasBuilding = true;
                collectingValues = true;
            } else if (type == RapidParser::DEFAULT) {
                if (hasBuilding) cases.push_back(building);
                building = TestCase{};
                building.isDefault = true;
                hasBuilding = true;
                collectingValues = false;
            } else if (term->getSymbol()->getText() == ":") {
                collectingValues = false;
            }
            // TEST / ENDTEST / ',' : no action needed.
        }
    }
    if (hasBuilding) cases.push_back(building);
    info.cases = std::move(cases);
    return info;
}

void Interpreter::execTest(RapidParser::TestStatementContext* ctx, Environment& env) {
    TestInfo info = splitTest(ctx);
    Value selector = evalExpression(info.selector, env);

    const TestCase* defaultCase = nullptr;
    for (auto& c : info.cases) {
        if (c.isDefault) {
            defaultCase = &c;
            continue;
        }
        for (auto* valExpr : c.values) {
            if (Value::equals(selector, evalExpression(valExpr, env))) {
                execStatements(c.body, env);
                return;
            }
        }
    }
    if (defaultCase) execStatements(defaultCase->body, env);
}

// ---- RETURN -----------------------------------------------------------------

void Interpreter::execReturn(RapidParser::ReturnStatementContext* ctx, Environment& env) {
    if (auto* e = ctx->expression()) {
        throw ReturnSignal{evalExpression(e, env), true};
    }
    throw ReturnSignal{Value(), false};
}

// ===========================================================================
// Move instructions
// ===========================================================================

MoveArgs Interpreter::evalMoveArgs(const std::vector<RapidParser::NamedOrPositionalExprContext*>& nopes,
                                   const std::vector<RapidParser::SwitchExprContext*>& switches,
                                   size_t numTargets, Environment& env) {
    MoveArgs result;
    if (nopes.size() != numTargets + 3) {
        throw error("internal error: Move instruction has " + std::to_string(nopes.size()) +
                     " arguments, expected " + std::to_string(numTargets + 3));
    }

    // Positions are fixed by the grammar (target(s), Speed, Zone, Tool);
    // any leading Name:= is just documentation and doesn't change position.
    for (size_t i = 0; i < numTargets; ++i) {
        result.targets.push_back(evalExpression(nopes[i]->expression(), env));
    }
    result.speed = evalExpression(nopes[numTargets]->expression(), env);
    result.zone = evalExpression(nopes[numTargets + 1]->expression(), env);
    result.tool = evalExpression(nopes[numTargets + 2]->expression(), env);

    // Switches are matched by name (V/T/Z/WObj), not position, since not all
    // of the (up to 3) optional switchExpr slots need be present.
    for (auto* sw : switches) {
        const std::string name = Environment::normalize(sw->IDENTIFIER()->getText());
        Value v = evalExpression(sw->expression(), env);
        if (name == "v") result.vOverride = v;
        else if (name == "t") result.tOverride = v;
        else if (name == "z") result.zOverride = v;
        else if (name == "wobj") result.wobj = v;
        // unrecognized switch names: still evaluated above (for side
        // effects), but otherwise ignored.
    }
    return result;
}

void Interpreter::execMoveAbsJ(RapidParser::MoveAbsJStatementContext* ctx, Environment& env) {
    MoveArgs m = evalMoveArgs(ctx->namedOrPositionalExpr(), ctx->switchExpr(), 1, env);
    if (ctx->IDENTIFIER()) m.conc = true;
    onMove("MoveAbsJ", m);
}

void Interpreter::execMoveJ(RapidParser::MoveJStatementContext* ctx, Environment& env) {
    MoveArgs m = evalMoveArgs(ctx->namedOrPositionalExpr(), ctx->switchExpr(), 1, env);
    if (ctx->IDENTIFIER()) m.conc = true;
    onMove("MoveJ", m);
}

void Interpreter::execMoveL(RapidParser::MoveLStatementContext* ctx, Environment& env) {
    MoveArgs m = evalMoveArgs(ctx->namedOrPositionalExpr(), ctx->switchExpr(), 1, env);
    if (ctx->IDENTIFIER()) m.conc = true;
    onMove("MoveL", m);
}

void Interpreter::execMoveC(RapidParser::MoveCStatementContext* ctx, Environment& env) {
    MoveArgs m = evalMoveArgs(ctx->namedOrPositionalExpr(), ctx->switchExpr(), 2, env);
    if (ctx->IDENTIFIER()) m.conc = true;
    onMove("MoveC", m);
}

void Interpreter::onMove(const std::string& instructionName, const MoveArgs& args) {
    std::cout << "[Move] " << instructionName << " ";
    if (args.targets.size() == 1) {
        std::cout << "target=" << args.targets[0].toDisplayString();
    } else if (args.targets.size() == 2) {
        std::cout << "cirpoint=" << args.targets[0].toDisplayString()
                   << " topoint=" << args.targets[1].toDisplayString();
    }
    std::cout << " speed=" << args.speed.toDisplayString()
              << " zone=" << args.zone.toDisplayString()
              << " tool=" << args.tool.toDisplayString();
    if (!args.wobj.isUndefined()) std::cout << " wobj=" << args.wobj.toDisplayString();
    if (!args.vOverride.isUndefined()) std::cout << " \\V=" << args.vOverride.toDisplayString();
    if (!args.tOverride.isUndefined()) std::cout << " \\T=" << args.tOverride.toDisplayString();
    if (!args.zOverride.isUndefined()) std::cout << " \\Z=" << args.zOverride.toDisplayString();
    if (args.conc) std::cout << " \\Conc";
    std::cout << std::endl;
}

// ===========================================================================
// Expressions
// ===========================================================================

Value Interpreter::evalExpression(RapidParser::ExpressionContext* ctx, Environment& env) {
    if (auto* c = dynamic_cast<RapidParser::ParenExprContext*>(ctx))
        return evalExpression(c->expression(), env);

    if (auto* c = dynamic_cast<RapidParser::AggregateExprContext*>(ctx))
        return evalAggregate(c->aggregate(), env);

    if (auto* c = dynamic_cast<RapidParser::FuncCallExprContext*>(ctx))
        return evalFunctionCall(c->functionCall(), env);

    if (auto* c = dynamic_cast<RapidParser::VarRefExprContext*>(ctx))
        return evalVariableReference(c->variableReference(), env);

    if (auto* c = dynamic_cast<RapidParser::LiteralExprContext*>(ctx))
        return evalLiteral(c->literal());

    if (auto* c = dynamic_cast<RapidParser::UnaryExprContext*>(ctx)) {
        Value v = evalExpression(c->expression(), env);
        return c->getStart()->getText() == "-" ? Value::neg(v) : v;
    }

    if (auto* c = dynamic_cast<RapidParser::MulExprContext*>(ctx)) {
        Value a = evalExpression(c->expression(0), env);
        Value b = evalExpression(c->expression(1), env);
        const std::string op = c->op->getText();
        if (op == "*") return Value::mul(a, b);
        if (op == "/") return Value::div(a, b);
        if (op == "DIV") return Value::intDiv(a, b);
        return Value::mod(a, b); // "MOD"
    }

    if (auto* c = dynamic_cast<RapidParser::AddExprContext*>(ctx)) {
        Value a = evalExpression(c->expression(0), env);
        Value b = evalExpression(c->expression(1), env);
        return c->op->getText() == "+" ? Value::add(a, b) : Value::sub(a, b);
    }

    if (auto* c = dynamic_cast<RapidParser::RelExprContext*>(ctx)) {
        Value a = evalExpression(c->expression(0), env);
        Value b = evalExpression(c->expression(1), env);
        const std::string op = c->op->getText();
        if (op == "=") return Value::boolean(Value::equals(a, b));
        if (op == "<>") return Value::boolean(!Value::equals(a, b));
        if (op == "<") return Value::boolean(Value::less(a, b));
        if (op == ">") return Value::boolean(Value::less(b, a));
        if (op == "<=") return Value::boolean(!Value::less(b, a));
        return Value::boolean(!Value::less(a, b)); // ">="
    }

    if (auto* c = dynamic_cast<RapidParser::NotExprContext*>(ctx))
        return Value::boolean(!evalExpression(c->expression(), env).asBool());

    if (auto* c = dynamic_cast<RapidParser::AndExprContext*>(ctx)) {
        // RAPID's AND/OR/XOR are not short-circuiting: evaluate both sides.
        bool a = evalExpression(c->expression(0), env).asBool();
        bool b = evalExpression(c->expression(1), env).asBool();
        return Value::boolean(a && b);
    }

    if (auto* c = dynamic_cast<RapidParser::XorOrExprContext*>(ctx)) {
        bool a = evalExpression(c->expression(0), env).asBool();
        bool b = evalExpression(c->expression(1), env).asBool();
        return Value::boolean(c->op->getText() == "OR" ? (a || b) : (a != b)); // XOR == !=
    }

    throw error("unrecognized expression node: " + ctx->getText());
}

Value Interpreter::evalAggregate(RapidParser::AggregateContext* ctx, Environment& env) {
    std::vector<Value> items;
    for (auto* e : ctx->expression()) items.push_back(evalExpression(e, env));
    return Value::array(std::move(items));
}

Value Interpreter::evalLiteral(RapidParser::LiteralContext* ctx) {
    if (auto* n = ctx->NUM()) return Value::num(std::stod(n->getText()));
    if (auto* s = ctx->STRING()) return Value::string(unescapeRapidString(s->getText()));
    if (ctx->TRUE()) return Value::boolean(true);
    if (ctx->FALSE()) return Value::boolean(false);
    throw error("unrecognized literal: " + ctx->getText());
}

Value Interpreter::evalVariableReference(RapidParser::VariableReferenceContext* ctx, Environment& env) {
    auto idents = ctx->IDENTIFIER();
    Value* slot = env.find(idents[0]->getText());
    if (!slot) throw error("undefined variable '" + idents[0]->getText() + "'");

    if (idents.size() > 1) {
        throw error("field access '." + idents[1]->getText() +
                     "' is not supported (no RECORD type info); use {index} instead");
    }

    Value current = *slot;
    for (auto* e : ctx->expression()) {
        const int idx = static_cast<int>(evalExpression(e, env).asNum());
        if (!current.isArray()) throw error("cannot index a non-array value with {" + std::to_string(idx) + "}");
        auto& arr = current.asArray();
        if (idx < 1 || idx > static_cast<int>(arr.size()))
            throw error("array index " + std::to_string(idx) + " out of range (1.." + std::to_string(arr.size()) + ")");
        current = arr[idx - 1];
    }
    return current;
}

void Interpreter::assignVariableReference(RapidParser::VariableReferenceContext* ctx, const Value& value, Environment& env) {
    auto idents = ctx->IDENTIFIER();
    if (idents.size() > 1) {
        throw error("field assignment '." + idents[1]->getText() +
                     "' is not supported (no RECORD type info); use {index} instead");
    }

    Value* slot = env.find(idents[0]->getText());
    if (!slot) throw error("undefined variable '" + idents[0]->getText() + "'");

    auto exprs = ctx->expression();
    if (exprs.empty()) {
        *slot = value;
        return;
    }

    Value* target = slot;
    for (size_t i = 0; i + 1 < exprs.size(); ++i) {
        const int idx = static_cast<int>(evalExpression(exprs[i], env).asNum());
        if (!target->isArray()) throw error("cannot index a non-array value with {" + std::to_string(idx) + "}");
        auto& arr = target->asArray();
        if (idx < 1 || idx > static_cast<int>(arr.size()))
            throw error("array index " + std::to_string(idx) + " out of range (1.." + std::to_string(arr.size()) + ")");
        target = &arr[idx - 1];
    }

    const int idx = static_cast<int>(evalExpression(exprs.back(), env).asNum());
    if (!target->isArray()) throw error("cannot index a non-array value with {" + std::to_string(idx) + "}");
    auto& arr = target->asArray();
    if (idx < 1 || idx > static_cast<int>(arr.size()))
        throw error("array index " + std::to_string(idx) + " out of range (1.." + std::to_string(arr.size()) + ")");
    arr[idx - 1] = value;
}

// ===========================================================================
// Calls (PROC/FUNC, builtins, parameter binding)
// ===========================================================================

std::vector<Value> Interpreter::evalPositionalArgs(RapidParser::ArgumentListContext* args, Environment& env) {
    std::vector<Value> result;
    if (!args) return result;
    for (auto* a : args->argument()) {
        if (auto* npe = a->namedOrPositionalExpr()) {
            result.push_back(evalExpression(npe->expression(), env));
        } else {
            // '\' IDENTIFIER (':=' expression)? -- switch arg: value if given, else TRUE
            result.push_back(a->expression() ? evalExpression(a->expression(), env) : Value::boolean(true));
        }
    }
    return result;
}

bool Interpreter::evalPresent(RapidParser::ArgumentListContext* args, Environment& env) {
    if (!args || args->argument().empty()) throw error("Present() requires one argument");
    auto* arg = args->argument(0);
    RapidParser::ExpressionContext* expr =
        arg->namedOrPositionalExpr() ? arg->namedOrPositionalExpr()->expression() : arg->expression();
    if (!expr) throw error("Present() argument must be a parameter name");

    auto* varRef = dynamic_cast<RapidParser::VarRefExprContext*>(expr);
    if (!varRef) throw error("Present() argument must be a parameter name");

    Value* slot = env.find(varRef->variableReference()->IDENTIFIER(0)->getText());
    return slot != nullptr && !slot->isUndefined();
}

Value Interpreter::evalFunctionCall(RapidParser::FunctionCallContext* ctx, Environment& env) {
    const std::string name = ctx->IDENTIFIER()->getText();
    const std::string key = Environment::normalize(name);

    if (key == "present") return Value::boolean(evalPresent(ctx->argumentList(), env));

    auto bIt = builtinFunctions_.find(key);
    if (bIt != builtinFunctions_.end()) {
        auto args = evalPositionalArgs(ctx->argumentList(), env);
        return bIt->second(*this, args);
    }

    if (functions_.count(key)) {
        return callRoutine(name, ctx->argumentList(), env, /*isFunction=*/true);
    }

    throw error("unknown function '" + name + "'");
}

void Interpreter::execIncrDecr(RapidParser::ProcedureCallStatementContext* ctx, Environment& env, bool incr) {
    const char* opName = incr ? "Incr" : "Decr";
    auto* args = ctx->argumentList();
    if (!args || args->argument().size() != 1) throw error(std::string(opName) + " expects exactly one argument");

    auto* arg = args->argument(0);
    RapidParser::ExpressionContext* expr =
        arg->namedOrPositionalExpr() ? arg->namedOrPositionalExpr()->expression() : arg->expression();
    auto* varRef = expr ? dynamic_cast<RapidParser::VarRefExprContext*>(expr) : nullptr;
    if (!varRef) throw error(std::string(opName) + " argument must be a variable");

    const double cur = evalExpression(expr, env).asNum();
    assignVariableReference(varRef->variableReference(), Value::num(cur + (incr ? 1.0 : -1.0)), env);
}

void Interpreter::execProcedureCall(RapidParser::ProcedureCallStatementContext* ctx, Environment& env) {
    const std::string name = ctx->IDENTIFIER()->getText();
    const std::string key = Environment::normalize(name);

    if (key == "incr") { execIncrDecr(ctx, env, true); return; }
    if (key == "decr") { execIncrDecr(ctx, env, false); return; }

    auto bIt = builtinProcedures_.find(key);
    if (bIt != builtinProcedures_.end()) {
        auto args = evalPositionalArgs(ctx->argumentList(), env);
        bIt->second(*this, args);
        return;
    }

    if (procedures_.count(key)) {
        callRoutine(name, ctx->argumentList(), env, /*isFunction=*/false);
        return;
    }

    throw error("unknown procedure '" + name + "'");
}

void Interpreter::bindArguments(RapidParser::ParameterListContext* params, RapidParser::ArgumentListContext* args,
                                 Environment& callerEnv, Environment& callee) {
    std::vector<ParamInfo> paramList;
    if (params) {
        for (auto* p : params->parameter()) {
            const bool optional = (p->getStart()->getText() == "\\");
            paramList.push_back({p->IDENTIFIER()->getText(), optional});
        }
    }

    std::vector<bool> bound(paramList.size(), false);
    for (auto& p : paramList) callee.declare(p.name, Value::undefined());

    auto findParam = [&](const std::string& name) -> int {
        const std::string key = Environment::normalize(name);
        for (size_t i = 0; i < paramList.size(); ++i)
            if (Environment::normalize(paramList[i].name) == key) return static_cast<int>(i);
        return -1;
    };

    if (args) {
        std::vector<RapidParser::ArgumentContext*> positional;

        // First pass: named (Name:=expr) and switch (\Name / \Name:=expr) arguments.
        for (auto* arg : args->argument()) {
            if (auto* npe = arg->namedOrPositionalExpr()) {
                if (auto* idTok = npe->IDENTIFIER()) {
                    const int idx = findParam(idTok->getText());
                    if (idx < 0) throw error("unknown named argument '" + idTok->getText() + "'");
                    callee.declare(paramList[idx].name, evalExpression(npe->expression(), callerEnv));
                    bound[idx] = true;
                } else {
                    positional.push_back(arg);
                }
            } else {
                const int idx = findParam(arg->IDENTIFIER()->getText());
                if (idx < 0) throw error("unknown switch argument '\\" + arg->IDENTIFIER()->getText() + "'");
                Value v = arg->expression() ? evalExpression(arg->expression(), callerEnv) : Value::boolean(true);
                callee.declare(paramList[idx].name, v);
                bound[idx] = true;
            }
        }

        // Second pass: positional arguments fill remaining unbound parameters in order.
        size_t pi = 0;
        for (auto* arg : positional) {
            while (pi < paramList.size() && bound[pi]) ++pi;
            if (pi >= paramList.size()) throw error("too many positional arguments");
            callee.declare(paramList[pi].name, evalExpression(arg->namedOrPositionalExpr()->expression(), callerEnv));
            bound[pi] = true;
            ++pi;
        }
    }

    for (size_t i = 0; i < paramList.size(); ++i) {
        if (!bound[i] && !paramList[i].optional)
            throw error("missing required argument '" + paramList[i].name + "'");
    }
}

Value Interpreter::callRoutine(const std::string& name, RapidParser::ArgumentListContext* args,
                                Environment& callerEnv, bool isFunction) {
    const std::string key = Environment::normalize(name);
    RapidParser::ParameterListContext* params = nullptr;
    std::vector<RapidParser::StatementContext*> body;

    if (isFunction) {
        auto it = functions_.find(key);
        if (it == functions_.end()) throw error("unknown function '" + name + "'");
        params = it->second->parameterList();
        body = it->second->statement();
    } else {
        auto it = procedures_.find(key);
        if (it == procedures_.end()) throw error("unknown procedure '" + name + "'");
        params = it->second->parameterList();
        body = it->second->statement();
    }

    if (callStack_.size() >= kMaxCallDepth) {
        throw error("maximum call depth (" + std::to_string(kMaxCallDepth) +
                     ") exceeded calling '" + name + "' (possible infinite recursion)");
    }

    Environment local(&globals_);
    bindArguments(params, args, callerEnv, local);

    callStack_.push_back(name);
    Value result;
    try {
        execStatements(body, local);
    } catch (ReturnSignal& r) {
        if (r.hasValue) result = r.value;
    } catch (GotoSignal& g) {
        auto err = error("label '" + g.label + "' not found in routine '" + name + "'");
        callStack_.pop_back();
        throw err;
    }
    callStack_.pop_back();
    return result;
}

// ===========================================================================
// Misc helpers
// ===========================================================================

std::string Interpreter::unescapeRapidString(const std::string& raw) {
    // raw includes the surrounding '"' characters.
    // Per the RAPID manual, '""' -> '"' and '\\' -> '\' (doubled-character
    // escapes). \NN control-code escapes are not handled.
    const std::string inner = raw.size() >= 2 ? raw.substr(1, raw.size() - 2) : raw;
    std::string out;
    out.reserve(inner.size());
    for (size_t i = 0; i < inner.size(); ++i) {
        if (inner[i] == '"' && i + 1 < inner.size() && inner[i + 1] == '"') {
            out += '"';
            ++i;
        } else if (inner[i] == '\\' && i + 1 < inner.size() && inner[i + 1] == '\\') {
            out += '\\';
            ++i;
        } else {
            out += inner[i];
        }
    }
    return out;
}

std::runtime_error Interpreter::error(const std::string& msg) const {
    std::ostringstream os;
    os << msg;
    if (!callStack_.empty()) {
        os << " (call stack: ";
        for (size_t i = 0; i < callStack_.size(); ++i) {
            if (i) os << " -> ";
            os << callStack_[i];
        }
        os << ")";
    }
    return std::runtime_error(os.str());
}

// ===========================================================================
// Built-in functions / procedures
// ===========================================================================

void Interpreter::registerBuiltins() {
    builtinFunctions_["numtostr"] = [](Interpreter&, std::vector<Value>& a) -> Value {
        if (a.empty()) throw std::runtime_error("NumToStr expects (num[, decimals])");
        const double v = a[0].asNum();
        int decimals = a.size() > 1 ? static_cast<int>(a[1].asNum()) : 6;
        if (decimals < 0) decimals = 0;
        std::ostringstream os;
        os << std::fixed << std::setprecision(decimals) << v;
        return Value::string(os.str());
    };

    builtinFunctions_["strtonum"] = [](Interpreter&, std::vector<Value>& a) -> Value {
        if (a.empty()) throw std::runtime_error("StrToNum expects (string)");
        try {
            return Value::num(std::stod(a[0].asString()));
        } catch (...) {
            throw std::runtime_error("StrToNum: '" + a[0].asString() + "' is not a valid number");
        }
    };

    builtinFunctions_["abs"] = [](Interpreter&, std::vector<Value>& a) -> Value {
        return Value::num(std::fabs(a.at(0).asNum()));
    };

    builtinFunctions_["sqrt"] = [](Interpreter&, std::vector<Value>& a) -> Value {
        const double v = a.at(0).asNum();
        if (v < 0) throw std::runtime_error("Sqrt of a negative number");
        return Value::num(std::sqrt(v));
    };

    builtinFunctions_["round"] = [](Interpreter&, std::vector<Value>& a) -> Value {
        const double v = a.at(0).asNum();
        const int decimals = a.size() > 1 ? static_cast<int>(a[1].asNum()) : 0;
        const double factor = std::pow(10.0, decimals);
        return Value::num(std::round(v * factor) / factor);
    };

    builtinFunctions_["trunc"] = [](Interpreter&, std::vector<Value>& a) -> Value {
        const double v = a.at(0).asNum();
        const int decimals = a.size() > 1 ? static_cast<int>(a[1].asNum()) : 0;
        const double factor = std::pow(10.0, decimals);
        return Value::num(std::trunc(v * factor) / factor);
    };

    // TPWrite "text" [\Num:=x] [\Bool:=b] ... -> all evaluated arguments are
    // concatenated and printed (simulated FlexPendant output).
    builtinProcedures_["tpwrite"] = [](Interpreter&, std::vector<Value>& a) {
        for (auto& v : a) std::cout << v.toDisplayString();
        std::cout << std::endl;
    };

    // WaitTime is not actually simulated (would make running test programs
    // slow); it just logs that it was reached.
    builtinProcedures_["waittime"] = [](Interpreter&, std::vector<Value>& a) {
        const double t = a.empty() ? 0.0 : a[0].asNum();
        std::cout << "[WaitTime] " << t << "s (not simulated)" << std::endl;
    };
}

} // namespace rapid
